### ISSUE TITLE
Naming of protocol functions.

### ISSUE THREAD

**Issue by robert-strandh** [s-expressionists/Incrementalist#1]
The names of protocol functions are currently not ideal.
ABSOLUTE-START-LINE-NUMBER should probably be called just
START-LINE-NUMBER since we are presenting a protocol that has only
absolute line numbers.  And START-COLUMN and END-COLUMN should
probably had a -NUMBER suffix.  But such changes would clash with
existing functions, some of which I think are internal and some apply
to wad descriptors.  So some thinking is required.

**Comment by scymtym** [comment]
I would prefer to simply remove the `-NUMBER` suffix from `ABSOLUTE-START-LINE-NUMBER` and keep everything else as-is. The distinction between `ABSOLUTE-START-LINE` and `START-LINE` makes sense to me as the latter is not always available.

**Comment by scymtym** [comment]
8602e8342a424a4923d71ef501cb7b870a93c313 solved this by removing the `-NUMBER` suffix from `ABSOLUTE-START-LINE-NUMBER`.
